channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightgbm==4.2.0
  - matplotlib==3.8.2
  - numpy==1.26.3
  - packaging==23.2
  - pandas==2.1.4
  - psutil==5.9.7
  - pyarrow==14.0.2
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
